sudo: required
dist: trusty
matrix:
  include:
  - os: linux
    sudo: false
  - os: osx
    osx_image: xcode9
language: node_js
node_js:
- 8
addons:
  apt:
    packages:
    - icnsutils
    - graphicsmagick
install:
- npm install
script:
- npm run test-ci
- npm run release
cache:
  apt: true
  directories:
  - "$HOME/.electron"
env:
  global:
    secure: rhpUbAD2CihllYOEuRHatU5HAArzA5mryJ0zHm0+oItEXvdzJObKGVoMvFoep6GVmOScbn+G41zUisDZKsJFQajzU+nT31VM3Zfd6CRji8awvtArsBS42Ani5i6Y5MDsaaPtGZMK9dwvgBBqcaEMKuJOsKjyd99+r4PIqTzS+uKIyWRp+bvMY54eai6L4KP/Q54CVF6Qubm4oZo35sgOvg9tKvytPQDNUFk1cDO0586n+9LAra0/VA8u/ytOB6s/uluCIhdfwPMM2z7IXbkCCGOpXeBDxdEeN+jNKzaZssCBM4FRlBI0j9SA/DztT/RJicIN2sovnFx2tKEHsx2TIZ19h8uAmshjD/VV+SK57Gc4GUE9Tea0av5iD6NofdToGGJ9Eu5XVquHlPydEsQNw02WHE0QDJPCQsYvBPELf7U36huPWSFNl9CJy5+Rlo8CxAjMpklhZLPtoubjpOYfnGeweF4PPE0qioCO6AJ0KPy/wM5H9MP6AmA4GJPXV6/yQJmpTW3W49H9Eg9vZZor9amoomCAnsaJSWuuoEhtpgT7sstI3V6lqvHbeK43yp7F2k2LkzjAa2gzZDumR6SjlcUppFbOffX8/j+UxWk4STWQQrPYA7gkKlWvLs0yMyG2b/taciat0sQGOevpNs1RmCYcCtXs0FfJbVQKkxYewyc=
