version: '{build}'

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 8 x64
  - npm install

test_script:
  - npm run test-ci

build_script:
  - npm run release:win64
